force-ide/objects/Dynamic_Image_Display__mdt.object
<CustomObject>
    <label>Dynamic Image Display</label>
    <pluralLabel>Dynamic Image Displays</pluralLabel>
</CustomObject>

force-app/main/default/objects/Dynamic_Image_Display__mdt/fields/Image_Config__c.field-meta.xml
<CustomField>
    <fullName>Image_Config__c</fullName>
    <label>Image Config</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DynamicImageDisplayController.cls
public class DynamicImageDisplayController {

    @AuraEnabled(cacheable=true)
    public static String getConfig(String configName)
    {
        List<Dynamic_Image_Display__mdt> recs = [SELECT Id, DeveloperName, Image_Config__c
                                      FROM Dynamic_Image_Display__mdt
                                     WHERE DeveloperName = :configName];
        
        String retVal = '';
        for (Dynamic_Image_Display__mdt rec : recs)
        {
            retVal = rec.Image_Config__c;
        }
        return retVal;
    }
}