force-ide/objects/Dynamic_Image_Display__mdt.object
<CustomObject>
    <label>Dynamic Image Display</label>
    <pluralLabel>Dynamic Image Displays</pluralLabel>
    <fields>
        <fullName>ArchiveName__c</fullName>
        <description>Static Resource name that is a zip/archive. Empty means the image is directly stored in Static Resources.</description>
        <label>ArchiveName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImageName__c</fullName>
        <description>Based on the Static Resource, direct is /image.png, inside an archive is combined with archivelocation + /image.png</description>
        <label>ImageName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LayerName__c</fullName>
        <label>LayerName</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

lightning-components/main/default/classes/DynamicImageDisplayConfig.cls
public with sharing class DynamicImageDisplayConfig
{
    public static List<Dynamic_Image_Display__mdt> getAllByGroupDID(String groupName)
    {
        List<Dynamic_Image_Display__mdt> recs = [SELECT Id, DeveloperName, LayerName__c, ArchiveName__c, ImageName__c
                                                 FROM Dynamic_Image_Display__mdt
                                                 WHERE Group__c = :groupName
                                                 ORDER BY DeveloperName];
        
        if(Test.isRunningTest())
        {
            if (recs != null && recs.size() <= 0)
            {
                Dynamic_Image_Display__mdt rec = new Dynamic_Image_Display__mdt(
                    DeveloperName = 'TestConfig',
                    LayerName__c = 'base',
                    ArchiveName__c = '',
                    ImageName__c = 'base.png');
                recs.add(rec);
            }
        }
        
        return recs;
    }
    
    public static List<String> getGroupsDID()
    {
        List<String> items = new List<String>();
        List<Dynamic_Image_Display__mdt> recs = [SELECT Group__c
                                      FROM Dynamic_Image_Display__mdt];
        
        if(Test.isRunningTest())
        {
            if (recs != null && recs.size() <= 0)
            {
                Dynamic_Image_Display__mdt rec = new Dynamic_Image_Display__mdt(
                    DeveloperName = 'TestConfig',
                    LayerName__c = 'base',
                    ArchiveName__c = '',
                    ImageName__c = 'base.png');
                recs.add(rec);
            }
        }
        
        for (Dynamic_Image_Display__mdt rec : recs)
        {
            String groupName = rec.Group__c;
            if (!items.contains(groupName)) {
                items.add(groupName);
            }
        }
        
        return items;
    }
}