force-ide/objects/TestEvent__e.object
<CustomObject>
    <label>TestEvent</label>
    <pluralLabel>TestEvents</pluralLabel>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

test-app/main/default/classes/GenerateEventControllerTest.cls
@IsTest
public class GenerateEventControllerTest
{
    @isTest
    static void testPublishEvents()
    {
        TestEvent__e evt = new TestEvent__e();
        evt.Message__c = '{test: "yes"}';
        
        GenerateEventController.publishEvent(evt);
        List<Database.SaveResult> results = GenerateEventController.publishEvents(evt);
        
        System.assertNotEquals(null, results);
    }

    @isTest
    static void testListMetadata()
    {
        List<Events_Generator__mdt> mdts = GenerateEventController.listMetadata('TestEvent');
        
        System.assertNotEquals(null, mdts);
    }
    
    @isTest
    static void testSelectMetadata()
    {
        Events_Generator__mdt mdt = GenerateEventController.selectMetadata('Go_Left');
        
        System.assertNotEquals(null, mdt);
    }
}